name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Updated to match recent stable Dart versions

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5 # Latest stable version
  rflutter_alert: ^2.0.4 # Added the rFlutter Alert package for alerts

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
